# Generated by Django 5.2.10 on 2026-02-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("identity", "0002_profile_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="agreed_to_terms",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Has accepted employee terms of use",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="terms_accepted_at",
            field=models.DateTimeField(
                blank=True, help_text="When employee terms were accepted", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="terms_accepted_ip",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP address when terms were accepted", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="terms_version",
            field=models.CharField(
                blank=True,
                help_text="Version of terms accepted (e.g., '2026.02')",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Deleted at"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Is deleted"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional data stored as JSON",
                verbose_name="Metadata",
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["agreed_to_terms", "is_active"], name="idx_profile_terms_active"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email_verified", "is_active"], name="idx_user_verified_active"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["status", "is_deleted"], name="idx_user_status"),
        ),
    ]
