# Generated by Django 5.2.10 on 2026-02-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Record version for optimistic locking",
                verbose_name="Version",
            ),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Record version for optimistic locking",
                verbose_name="Version",
            ),
        ),
    ]
