# Generated by Django 6.0.2 on 2026-02-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captureevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("page_view", "Page View"),
                    ("form_intent", "Form Intent"),
                    ("form_attempt", "Form Attempt"),
                    ("form_success", "Form Success"),
                    ("form_error", "Form Error"),
                    ("cta_click", "CTA Click"),
                    ("scroll_milestone", "Scroll Milestone"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
