# Generated by Django 6.0.2 on 2026-04-05 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_fingerprint", "0001_initial"),
        (
            "contact_identity",
            "0003_identity_display_name_identity_lifecycle_global_and_more",
        ),
        ("launches", "0001_initial"),
        ("tracking", "0002_add_form_intent_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaptureIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Record version for optimistic locking",
                        verbose_name="Version",
                    ),
                ),
                (
                    "capture_token",
                    models.UUIDField(
                        db_index=True,
                        help_text="UUID from the page load session.",
                        unique=True,
                    ),
                ),
                (
                    "page_path",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Landing path observed when the intent was captured.",
                        max_length=500,
                    ),
                ),
                (
                    "visitor_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("email_hint", models.CharField(blank=True, max_length=255)),
                ("phone_hint", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "capture_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="capture_intents",
                        to="launches.capturepage",
                    ),
                ),
                (
                    "fingerprint_identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="capture_intents",
                        to="contact_fingerprint.fingerprintidentity",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="capture_intents",
                        to="contact_identity.identity",
                    ),
                ),
            ],
            options={
                "db_table": "tracking_capture_intent",
                "ordering": ["-updated_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["status", "updated_at"],
                        name="tracking_ca_status_30c2d9_idx",
                    ),
                    models.Index(
                        fields=["capture_page", "status"],
                        name="tracking_ca_capture_b5dd2a_idx",
                    ),
                    models.Index(
                        fields=["identity", "status"],
                        name="tracking_ca_identit_c4a269_idx",
                    ),
                    models.Index(
                        fields=["visitor_id", "updated_at"],
                        name="tracking_ca_visitor_622052_idx",
                    ),
                ],
            },
        ),
    ]
