# Generated by Django 6.0.2 on 2026-02-10 20:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contact_identity", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FingerprintIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Record version for optimistic locking",
                        verbose_name="Version",
                    ),
                ),
                (
                    "hash",
                    models.CharField(
                        db_index=True,
                        help_text="visitorId from FingerprintJS Pro",
                        max_length=64,
                        unique=True,
                        verbose_name="Visitor ID hash",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0,
                        help_text="FingerprintJS confidence (0.0 - 1.0)",
                        verbose_name="Confidence score",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        default="unknown",
                        help_text="mobile, tablet, desktop, unknown",
                        max_length=50,
                        verbose_name="Device type",
                    ),
                ),
                (
                    "visitor_found",
                    models.BooleanField(
                        default=False,
                        help_text="Whether FingerprintJS found a returning visitor",
                        verbose_name="Visitor found",
                    ),
                ),
                (
                    "device_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parsed device details (model, brand, screen, etc.)",
                        verbose_name="Device info",
                    ),
                ),
                (
                    "browser_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Browser name, version, engine, capabilities",
                        verbose_name="Browser info",
                    ),
                ),
                (
                    "geo_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Country, city, timezone, coordinates, accuracy",
                        verbose_name="Geolocation info",
                    ),
                ),
                (
                    "browser",
                    models.CharField(blank=True, max_length=50, verbose_name="Browser"),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Operating system"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User agent")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="First seen"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Last seen"
                    ),
                ),
                (
                    "is_master",
                    models.BooleanField(
                        default=False,
                        help_text="Primary fingerprint for the linked identity",
                        verbose_name="Is master fingerprint",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fingerprints",
                        to="contact_identity.identity",
                        verbose_name="Identity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fingerprint Identity",
                "verbose_name_plural": "Fingerprint Identities",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FingerprintEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Record version for optimistic locking",
                        verbose_name="Version",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="page_view, form_submit, click, etc.",
                        max_length=100,
                        verbose_name="Event type",
                    ),
                ),
                (
                    "page_url",
                    models.URLField(
                        blank=True, max_length=2048, null=True, verbose_name="Page URL"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, verbose_name="Event timestamp"),
                ),
                (
                    "user_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User-provided data (form fields, UTM params, etc.)",
                        verbose_name="User data",
                    ),
                ),
                (
                    "event_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Technical event data (scroll position, element, etc.)",
                        verbose_name="Event data",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="Session ID",
                    ),
                ),
                (
                    "fingerprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="contact_fingerprint.fingerprintidentity",
                        verbose_name="Fingerprint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fingerprint Event",
                "verbose_name_plural": "Fingerprint Events",
                "ordering": ["-timestamp"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FingerprintContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Record version for optimistic locking",
                        verbose_name="Version",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(verbose_name="Contact ID"),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                        ],
                        default="unverified",
                        max_length=20,
                        verbose_name="Verification status",
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(auto_now_add=True, verbose_name="First seen"),
                ),
                (
                    "last_seen",
                    models.DateTimeField(auto_now=True, verbose_name="Last seen"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            models.Q(
                                ("app_label", "contact_email"),
                                ("model", "contactemail"),
                            ),
                            models.Q(
                                ("app_label", "contact_phone"),
                                ("model", "contactphone"),
                            ),
                            _connector="OR",
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Contact type",
                    ),
                ),
                (
                    "fingerprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="contact_fingerprint.fingerprintidentity",
                        verbose_name="Fingerprint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fingerprint Contact",
                "verbose_name_plural": "Fingerprint Contacts",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="fingerprintidentity",
            index=models.Index(
                fields=["device_type", "browser"], name="contact_fin_device__78602c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fingerprintidentity",
            index=models.Index(
                fields=["last_seen"], name="contact_fin_last_se_05379a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fingerprintidentity",
            index=models.Index(
                fields=["identity"], name="contact_fin_identit_cf76a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fingerprintidentity",
            index=models.Index(
                fields=["confidence_score"], name="contact_fin_confide_e26d17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fingerprintevent",
            index=models.Index(
                fields=["fingerprint", "-timestamp"],
                name="contact_fin_fingerp_87cfab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fingerprintevent",
            index=models.Index(
                fields=["event_type", "-timestamp"],
                name="contact_fin_event_t_e18d0d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fingerprintevent",
            index=models.Index(
                fields=["session_id"], name="contact_fin_session_e19fc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fingerprintcontact",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="contact_fin_content_cd3273_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fingerprintcontact",
            index=models.Index(
                fields=["fingerprint"], name="contact_fin_fingerp_0ede4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fingerprintcontact",
            index=models.Index(
                fields=["verification_status"], name="contact_fin_verific_4f3ca0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fingerprintcontact",
            unique_together={("content_type", "object_id", "fingerprint")},
        ),
    ]
