# Generated by Django 6.0.2 on 2026-02-10 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Identity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Record version for optimistic locking",
                        verbose_name="Version",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("merged", "Merged"),
                            ("inactive", "Inactive"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last seen"
                    ),
                ),
                (
                    "first_seen_source",
                    models.CharField(
                        blank=True,
                        help_text="Source where this identity was first observed (e.g., form, API)",
                        max_length=100,
                        null=True,
                        verbose_name="First seen source",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Overall confidence score (0.0 - 1.0)",
                        verbose_name="Confidence score",
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        help_text="The identity this was merged into",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_identities",
                        to="contact_identity.identity",
                        verbose_name="Merged into",
                    ),
                ),
            ],
            options={
                "verbose_name": "Identity",
                "verbose_name_plural": "Identities",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IdentityHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Record version for optimistic locking",
                        verbose_name="Version",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("MERGE", "Identity Merge"),
                            ("STATUS_CHANGE", "Status Change"),
                            ("CONTACT_ADDED", "Contact Added"),
                            ("CONTACT_REMOVED", "Contact Removed"),
                            ("FINGERPRINT_LINKED", "Fingerprint Linked"),
                            ("CONFIDENCE_UPDATE", "Confidence Score Update"),
                            ("UPDATE", "General Update"),
                        ],
                        max_length=50,
                        verbose_name="Operation type",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Timestamp"
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context about the operation (JSON)",
                        verbose_name="Details",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="contact_identity.identity",
                        verbose_name="Identity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Identity History",
                "verbose_name_plural": "Identity Histories",
                "ordering": ["-timestamp"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="identity",
            index=models.Index(fields=["status"], name="contact_ide_status_b50631_idx"),
        ),
        migrations.AddIndex(
            model_name="identity",
            index=models.Index(
                fields=["merged_into"], name="contact_ide_merged__6242bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="identity",
            index=models.Index(
                fields=["last_seen"], name="contact_ide_last_se_9a0acd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="identity",
            index=models.Index(
                fields=["confidence_score"], name="contact_ide_confide_c86b5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="identityhistory",
            index=models.Index(
                fields=["identity", "-timestamp"], name="contact_ide_identit_681871_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="identityhistory",
            index=models.Index(
                fields=["operation_type"], name="contact_ide_operati_b3af09_idx"
            ),
        ),
    ]
