# Generated by Django 6.0.2 on 2026-02-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_identity", "0002_attribution"),
        ("contacts", "0005_alter_additionalemail_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="identity",
            name="display_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name for display (from capture form or inferred from email)",
                max_length=255,
                verbose_name="Display name",
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="lifecycle_global",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSONB cache of cross-launch lifecycle data (updated by signals/tasks)",
                verbose_name="Global lifecycle",
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="operator_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Free-form notes by the operator about this identity",
                verbose_name="Operator notes",
            ),
        ),
        migrations.AddField(
            model_name="identity",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Manual operator tags + automatic launch tags",
                related_name="identities",
                to="contacts.tag",
                verbose_name="Tags",
            ),
        ),
    ]
