# Generated by Django 5.2.10 on 2026-02-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254)),
                ("phone", models.CharField(blank=True, db_index=True, max_length=50)),
                ("company", models.CharField(blank=True, max_length=255)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("import", "CSV Import"),
                            ("form", "Form Submission"),
                            ("api", "API"),
                            ("integration", "Integration"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("prospect", "Prospect"),
                            ("customer", "Customer"),
                            ("churned", "Churned"),
                            ("inactive", "Inactive"),
                        ],
                        db_index=True,
                        default="lead",
                        max_length=20,
                    ),
                ),
                ("lead_score", models.PositiveIntegerField(default=0)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("email_verified", models.BooleanField(default=False)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                ("phone_verified", models.BooleanField(default=False)),
                ("phone_verified_at", models.DateTimeField(blank=True, null=True)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("label", models.CharField(default="work", max_length=50)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Contact Email",
                "verbose_name_plural": "Contact Emails",
            },
        ),
        migrations.CreateModel(
            name="ContactNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("note", "Note"),
                            ("call", "Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("task", "Task"),
                        ],
                        default="note",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Note",
                "verbose_name_plural": "Contact Notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                ("phone", models.CharField(max_length=50)),
                ("label", models.CharField(default="mobile", max_length=50)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Contact Phone",
                "verbose_name_plural": "Contact Phones",
            },
        ),
        migrations.CreateModel(
            name="CustomFieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("datetime", "Date & Time"),
                            ("boolean", "Yes/No"),
                            ("select", "Dropdown"),
                            ("multiselect", "Multi-select"),
                            ("url", "URL"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(blank=True, default=list)),
                ("is_required", models.BooleanField(default=False)),
                ("default_value", models.CharField(blank=True, max_length=255)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Custom Field",
                "verbose_name_plural": "Custom Fields",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
                ("color", models.CharField(default="#6366f1", max_length=7)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["name"],
            },
        ),
    ]
