# Generated by Django 6.0.2 on 2026-02-12 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_rename_models_add_identity_fk"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="additionalemail",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="additionalemail",
            name="contact",
        ),
        migrations.AlterUniqueTogether(
            name="additionalphone",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="additionalphone",
            name="contact",
        ),
        migrations.RemoveIndex(
            model_name="contact",
            name="contacts_co_email_25f973_idx",
        ),
        migrations.RemoveIndex(
            model_name="contact",
            name="contacts_co_phone_5a60c7_idx",
        ),
        migrations.RemoveIndex(
            model_name="contact",
            name="contacts_co_status_e1d017_idx",
        ),
        migrations.RemoveIndex(
            model_name="contact",
            name="contacts_co_owner_i_f61fc2_idx",
        ),
        migrations.RemoveField(
            model_name="contactnote",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="contactnote",
            name="author",
        ),
        migrations.DeleteModel(
            name="AdditionalEmail",
        ),
        migrations.DeleteModel(
            name="AdditionalPhone",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="identity",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="tags",
        ),
        migrations.DeleteModel(
            name="ContactNote",
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
