# Generated by Django 6.0.2 on 2026-02-10 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contact_identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Record version for optimistic locking",
                        verbose_name="Version",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        db_index=True,
                        help_text="Normalized phone number (E.164 format when possible)",
                        max_length=255,
                        unique=True,
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "original_value",
                    models.CharField(
                        blank=True,
                        help_text="Raw phone as entered by the user before normalization",
                        max_length=255,
                        verbose_name="Original value",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        default="55",
                        help_text="Phone country code (default: 55 for Brazil)",
                        max_length=10,
                        verbose_name="Country code",
                    ),
                ),
                (
                    "phone_type",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("landline", "Landline"),
                            ("voip", "VoIP"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="Phone type",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is verified"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified at"
                    ),
                ),
                (
                    "is_whatsapp",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this number is registered on WhatsApp",
                        verbose_name="Is WhatsApp",
                    ),
                ),
                (
                    "is_sms_capable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether SMS can be delivered to this number",
                        verbose_name="SMS capable",
                    ),
                ),
                (
                    "is_dnc",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this number is on a Do Not Contact list",
                        verbose_name="Do not contact",
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(auto_now_add=True, verbose_name="First seen"),
                ),
                (
                    "last_seen",
                    models.DateTimeField(auto_now=True, verbose_name="Last seen"),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_contacts",
                        to="contact_identity.identity",
                        verbose_name="Identity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Phone",
                "verbose_name_plural": "Contact Phones",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["is_verified"], name="contact_pho_is_veri_5b8b83_idx"
                    ),
                    models.Index(
                        fields=["identity"], name="contact_pho_identit_290269_idx"
                    ),
                    models.Index(
                        fields=["country_code"], name="contact_pho_country_c37f75_idx"
                    ),
                    models.Index(
                        fields=["phone_type"], name="contact_pho_phone_t_b3eb00_idx"
                    ),
                    models.Index(
                        fields=["first_seen"], name="contact_pho_first_s_152f13_idx"
                    ),
                ],
            },
        ),
    ]
