# Generated by Django 6.0.2 on 2026-02-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_phone", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactphone",
            name="value_sha256",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Meta-standard SHA-256 of digit-only phone (for CAPI + cookies)",
                max_length=64,
                verbose_name="SHA-256 hash",
            ),
        ),
    ]
