# Generated by Django 6.0.2 on 2026-04-10 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "identity",
            "0004_user_setup_status_usertoken_emailverificationtoken_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="setup_status",
        ),
    ]
