# Generated by Django 6.0.2 on 2026-04-05 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadIntegrationOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Record version for optimistic locking",
                        verbose_name="Version",
                    ),
                ),
                ("capture_token", models.UUIDField(db_index=True)),
                (
                    "integration_type",
                    models.CharField(
                        choices=[("n8n", "N8N"), ("meta_capi", "Meta CAPI")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("response_data", models.JSONField(blank=True, default=dict)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                (
                    "identity_public_id",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                (
                    "next_retry_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "capture_submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integration_outbox_entries",
                        to="ads.capturesubmission",
                    ),
                ),
            ],
            options={
                "db_table": "landing_lead_integration_outbox",
                "ordering": ["created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["status", "next_retry_at"],
                        name="landing_lea_status_90626e_idx",
                    ),
                    models.Index(
                        fields=["integration_type", "status"],
                        name="landing_lea_integra_bb2022_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("capture_token", "integration_type"),
                        name="uniq_lio_capture_token_type",
                    )
                ],
            },
        ),
    ]
