# Generated by Django 6.0.2 on 2026-04-06 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
        (
            "contact_identity",
            "0003_identity_display_name_identity_lifecycle_global_and_more",
        ),
        ("landing", "0001_initial"),
        ("launches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadCaptureIdempotencyKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Record version for optimistic locking",
                        verbose_name="Version",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("capture_token", models.UUIDField(db_index=True)),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("email_normalized", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("thank_you_url", models.CharField(blank=True, max_length=500)),
                (
                    "capture_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="idempotency_keys",
                        to="launches.capturepage",
                    ),
                ),
                (
                    "capture_submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="idempotency_keys",
                        to="ads.capturesubmission",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_capture_idempotency_keys",
                        to="contact_identity.identity",
                    ),
                ),
            ],
            options={
                "db_table": "landing_lead_capture_idempotency",
                "ordering": ["-updated_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["status", "updated_at"],
                        name="landing_lea_status_6b4d23_idx",
                    ),
                    models.Index(
                        fields=["capture_token", "email_normalized"],
                        name="landing_lea_capture_6ef130_idx",
                    ),
                    models.Index(
                        fields=["request_id", "email_normalized"],
                        name="landing_lea_request_a054bf_idx",
                    ),
                ],
            },
        ),
    ]
