# Generated by Django 6.0.2 on 2026-02-10 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contact_identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Record version for optimistic locking",
                        verbose_name="Version",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Email address",
                    ),
                ),
                (
                    "original_value",
                    models.CharField(
                        blank=True,
                        help_text="Raw email as entered by the user before normalization",
                        max_length=255,
                        verbose_name="Original value",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Extracted domain (e.g., gmail.com)",
                        max_length=100,
                        verbose_name="Domain",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is verified"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified at"
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(auto_now_add=True, verbose_name="First seen"),
                ),
                (
                    "last_seen",
                    models.DateTimeField(auto_now=True, verbose_name="Last seen"),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_contacts",
                        to="contact_identity.identity",
                        verbose_name="Identity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Email",
                "verbose_name_plural": "Contact Emails",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["is_verified"], name="contact_ema_is_veri_464323_idx"
                    ),
                    models.Index(
                        fields=["identity"], name="contact_ema_identit_090c81_idx"
                    ),
                    models.Index(
                        fields=["domain"], name="contact_ema_domain_26001a_idx"
                    ),
                    models.Index(
                        fields=["first_seen"], name="contact_ema_first_s_cf18d4_idx"
                    ),
                ],
            },
        ),
    ]
