# Generated by Django 6.0.2 on 2026-02-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_email", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactemail",
            name="is_dnc",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this email is on a Do Not Contact list",
                verbose_name="Do not contact",
            ),
        ),
        migrations.AddField(
            model_name="contactemail",
            name="lifecycle_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Verification"),
                    ("active", "Active"),
                    ("invalid", "Invalid"),
                    ("bounced_soft", "Soft Bounce"),
                    ("bounced_hard", "Hard Bounce"),
                    ("complained", "Complained"),
                    ("unsubscribed", "Unsubscribed"),
                ],
                db_index=True,
                default="pending",
                help_text="Email health state machine",
                max_length=20,
                verbose_name="Lifecycle status",
            ),
        ),
        migrations.AddField(
            model_name="contactemail",
            name="quality_score",
            field=models.FloatField(
                default=0.0,
                help_text="Computed email quality (0.0 - 1.0)",
                verbose_name="Quality score",
            ),
        ),
    ]
