# Generated by Django 6.0.2 on 2026-02-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contact_email",
            "0002_contactemail_is_dnc_contactemail_lifecycle_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contactemail",
            name="value_sha256",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Meta-standard SHA-256 of normalized email (for CAPI + cookies)",
                max_length=64,
                verbose_name="SHA-256 hash",
            ),
        ),
    ]
