# Generated by Django 5.2.10 on 2026-02-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Record version for optimistic locking",
                verbose_name="Version",
            ),
        ),
        migrations.AddField(
            model_name="contactemail",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Record version for optimistic locking",
                verbose_name="Version",
            ),
        ),
        migrations.AddField(
            model_name="contactnote",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Record version for optimistic locking",
                verbose_name="Version",
            ),
        ),
        migrations.AddField(
            model_name="contactphone",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Record version for optimistic locking",
                verbose_name="Version",
            ),
        ),
        migrations.AddField(
            model_name="customfielddefinition",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Record version for optimistic locking",
                verbose_name="Version",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Record version for optimistic locking",
                verbose_name="Version",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                blank=True,
                default="#6366f1",
                help_text="Hex color code (e.g., #6366f1)",
                max_length=7,
                verbose_name="Color",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(db_index=True, max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                help_text="URL-safe identifier (auto-generated from name)",
                max_length=100,
                unique=True,
                verbose_name="Slug",
            ),
        ),
    ]
