# Generated by Django 6.0.2 on 2026-02-16 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contact_fingerprint", "0001_initial"),
        (
            "contact_identity",
            "0003_identity_display_name_identity_lifecycle_global_and_more",
        ),
        ("launches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackingDailySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_path", models.CharField(max_length=500)),
                ("page_category", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("event_type", models.CharField(max_length=20)),
                ("event_count", models.IntegerField()),
                ("unique_visitors", models.IntegerField()),
                ("unique_ips", models.IntegerField()),
            ],
            options={
                "db_table": "tracking_daily_summary",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TrackingPageMetrics",
            fields=[
                (
                    "page_path",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                ("page_category", models.CharField(max_length=20)),
                ("views", models.IntegerField()),
                ("attempts", models.IntegerField()),
                ("conversions", models.IntegerField()),
                ("errors", models.IntegerField()),
                (
                    "conversion_rate_pct",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
            options={
                "db_table": "tracking_page_metrics",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DeviceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Record version for optimistic locking",
                        verbose_name="Version",
                    ),
                ),
                (
                    "profile_hash",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("browser_family", models.CharField(max_length=50)),
                ("browser_version", models.CharField(max_length=20)),
                ("browser_engine", models.CharField(blank=True, max_length=30)),
                ("os_family", models.CharField(max_length=50)),
                ("os_version", models.CharField(blank=True, max_length=20)),
                ("device_type", models.CharField(max_length=20)),
                ("device_brand", models.CharField(blank=True, max_length=50)),
                ("device_model", models.CharField(blank=True, max_length=50)),
                ("is_bot", models.BooleanField(default=False)),
                ("bot_name", models.CharField(blank=True, max_length=100)),
                ("bot_category", models.CharField(blank=True, max_length=50)),
                (
                    "user_agent_sample",
                    models.TextField(
                        blank=True, help_text="One example UA string for debugging."
                    ),
                ),
            ],
            options={
                "db_table": "tracking_device_profile",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["browser_family", "os_family"],
                        name="tracking_de_browser_3ab5a3_idx",
                    ),
                    models.Index(
                        fields=["device_type"], name="tracking_de_device__ac3c92_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CaptureEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Record version for optimistic locking",
                        verbose_name="Version",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Page View"),
                            ("form_attempt", "Form Attempt"),
                            ("form_success", "Form Success"),
                            ("form_error", "Form Error"),
                            ("cta_click", "CTA Click"),
                            ("scroll_milestone", "Scroll Milestone"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "capture_token",
                    models.UUIDField(
                        db_index=True,
                        help_text="UUID generated on GET, passed as prop + hidden input. Links page_view -> form_attempt -> form_success of the same session.",
                    ),
                ),
                (
                    "page_path",
                    models.CharField(
                        db_index=True,
                        help_text="Path: /inscrever-wh-rc-v3/, /obrigado-wh-rc-v3/, /suporte/, etc.",
                        max_length=500,
                    ),
                ),
                (
                    "page_category",
                    models.CharField(
                        choices=[
                            ("capture", "Pagina de Captura"),
                            ("checkout", "Checkout"),
                            ("thank_you", "Obrigado"),
                            ("support", "Suporte"),
                            ("sales", "Pagina de Vendas"),
                            ("content", "Conteudo"),
                            ("legal", "Pagina Legal"),
                            ("dashboard", "Dashboard"),
                            ("other", "Outro"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=20,
                    ),
                ),
                ("page_url", models.URLField(blank=True, max_length=500)),
                ("referrer", models.URLField(blank=True, max_length=500)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "geo_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="GeoIP data: {city, country, lat, long, asn, isp}",
                    ),
                ),
                (
                    "visitor_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("utm_data", models.JSONField(blank=True, default=dict)),
                ("accept_language", models.CharField(blank=True, max_length=100)),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra data: validation errors, scroll_depth, time_on_page, cta_label, etc.",
                    ),
                ),
                (
                    "capture_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="launches.capturepage",
                    ),
                ),
                (
                    "fingerprint_identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracking_events",
                        to="contact_fingerprint.fingerprintidentity",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracking_events",
                        to="contact_identity.identity",
                    ),
                ),
                (
                    "device_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="tracking.deviceprofile",
                    ),
                ),
            ],
            options={
                "db_table": "tracking_capture_event",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["page_path", "event_type", "created_at"],
                        name="tracking_ca_page_pa_1f1149_idx",
                    ),
                    models.Index(
                        fields=["page_category", "event_type", "created_at"],
                        name="tracking_ca_page_ca_4ef446_idx",
                    ),
                    models.Index(
                        fields=["capture_token", "event_type"],
                        name="tracking_ca_capture_2f6268_idx",
                    ),
                    models.Index(
                        fields=["visitor_id", "created_at"],
                        name="tracking_ca_visitor_6bdb9e_idx",
                    ),
                    models.Index(
                        condition=models.Q(("event_type", "page_view")),
                        fields=["created_at"],
                        name="idx_cev_pageview_ts",
                    ),
                ],
            },
        ),
    ]
