# Generated by Django 6.0.2 on 2026-02-17 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "contact_identity",
            "0003_identity_display_name_identity_lifecycle_global_and_more",
        ),
        ("launches", "0001_initial"),
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdProvider",
            fields=[
                (
                    "code",
                    models.CharField(
                        help_text='Unique code: "meta", "google", "tiktok", "organic", "direct".',
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Display name: "Meta Ads", "Google Ads", etc.',
                        max_length=100,
                    ),
                ),
                (
                    "api_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider API config: base_url, auth_type, insights_endpoint, rate_limit_per_minute, available_metrics.",
                    ),
                ),
                (
                    "source_patterns",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Auto-detection patterns: utm_source_patterns (regex list), vk_source_values, click_id_param.",
                    ),
                ),
                (
                    "naming_convention",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="UTM parsing instructions: utm_medium_separator, utm_medium_segments, utm_campaign_separator, etc.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Provider",
                "verbose_name_plural": "Ad Providers",
                "db_table": "ads_provider",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AdCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Record version for optimistic locking",
                        verbose_name="Version",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Provider campaign ID, e.g. Meta Campaign ID. Empty for organic.",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text='Campaign name, e.g. "[WH0126] [Captacao] [Quente] [Repasse] [V1] - Melhores 2".'
                    ),
                ),
                (
                    "funnel_stage",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Funnel stage: "capture", "sales", "checkout", "content", "retention".',
                        max_length=20,
                    ),
                ),
                (
                    "parsed_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Data derived from naming convention: temperature, page_version, variant_name, raw_campaign_string.",
                    ),
                ),
                (
                    "api_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Enriched from provider API: spend, impressions, reach, cpm, cpl, last_synced_at.",
                    ),
                ),
                (
                    "interest",
                    models.ForeignKey(
                        blank=True,
                        help_text="Auto-extracted from campaign name ([Repasse] -> Interest).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ad_campaigns",
                        to="launches.interest",
                    ),
                ),
                (
                    "launch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Auto-extracted from campaign name (WH0126 -> Launch.launch_code).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ad_campaigns",
                        to="launches.launch",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="ads.adprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Campaign",
                "verbose_name_plural": "Ad Campaigns",
                "db_table": "ads_campaign",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AdGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Record version for optimistic locking",
                        verbose_name="Version",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Provider adset ID, e.g. Meta Adset ID. Empty for organic.",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text='Adset name, e.g. "01 - [Mix Quente] [AD364_RC_CAPT_WH0725]".'
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        db_index=True,
                        default="paid",
                        help_text='Traffic payment type: "paid" or "organic".',
                        max_length=10,
                    ),
                ),
                (
                    "audience_temperature",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text='Audience temperature: "hot", "cold", "warm".',
                        max_length=10,
                    ),
                ),
                (
                    "parsed_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Derived from naming convention: audience_type, sequence_number, creative_codes_in_name, raw_medium_string.",
                    ),
                ),
                (
                    "api_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Enriched from provider API: spend, impressions, reach, CPM per adset.",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        help_text="Resolves provider: ad_group.campaign.provider.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_groups",
                        to="ads.adcampaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Group",
                "verbose_name_plural": "Ad Groups",
                "db_table": "ads_group",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AdPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text='Platform code: "instagram", "facebook", "youtube", etc.',
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Display name: "Instagram", "Facebook", etc.',
                        max_length=100,
                    ),
                ),
                (
                    "platform_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Platform metadata: icon_url, valid_placements list, default_placement.",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platforms",
                        to="ads.adprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Platform",
                "verbose_name_plural": "Ad Platforms",
                "db_table": "ads_platform",
                "ordering": ["provider", "code"],
            },
        ),
        migrations.CreateModel(
            name="AdCreative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Record version for optimistic locking",
                        verbose_name="Version",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Provider ad ID (from vk_ad_id). Empty for organic.",
                        max_length=50,
                    ),
                ),
                (
                    "creative_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Sequential creative code: "AD364" (prefix + number).',
                        max_length=20,
                    ),
                ),
                (
                    "full_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Full utm_content code: "AD364_RC_CAPT_WH0725".',
                        max_length=100,
                    ),
                ),
                (
                    "original_launch_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Launch where creative was originally created: "WH0725". May differ from the current launch.',
                        max_length=20,
                    ),
                ),
                (
                    "funnel_stage",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Funnel stage from code: "capture" (CAPT), "sales", etc.',
                        max_length=20,
                    ),
                ),
                (
                    "provider_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Provider-specific data: ad_name, format, thumbnail_url, performance metrics (ctr, cpl).",
                    ),
                ),
                (
                    "original_interest",
                    models.ForeignKey(
                        blank=True,
                        help_text="The interest this creative was made for (RC, TD), independent of the campaign it runs in.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="creatives",
                        to="launches.interest",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creatives",
                        to="ads.adprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Creative",
                "verbose_name_plural": "Ad Creatives",
                "db_table": "ads_creative",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrafficSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Record version for optimistic locking",
                        verbose_name="Version",
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        help_text='Placement: "reels", "feed", "stories", "search", "shorts".',
                        max_length=50,
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        help_text="Resolves provider automatically: source.platform.provider.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traffic_sources",
                        to="ads.adplatform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Traffic Source",
                "verbose_name_plural": "Traffic Sources",
                "db_table": "ads_traffic_source",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CaptureSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Record version for optimistic locking",
                        verbose_name="Version",
                    ),
                ),
                (
                    "email_raw",
                    models.CharField(
                        help_text="Exact form value (before normalization).",
                        max_length=254,
                    ),
                ),
                (
                    "phone_raw",
                    models.CharField(help_text="Exact form value.", max_length=30),
                ),
                (
                    "click_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="fbclid / gclid / ttclid — unique per click. Essential for Meta CAPI.",
                        max_length=200,
                    ),
                ),
                (
                    "visitor_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="FingerprintJS visitorId.",
                        max_length=100,
                    ),
                ),
                (
                    "capture_token",
                    models.UUIDField(
                        db_index=True,
                        help_text="Logical join with CaptureEvents (not FK). UUID from GET.",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "geo_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="GeoIP: {city, region, country, lat, lng, asn, isp}.",
                    ),
                ),
                (
                    "n8n_status",
                    models.CharField(
                        db_index=True,
                        default="pending",
                        help_text='Status: "pending", "sent", "failed", "skipped".',
                        max_length=20,
                    ),
                ),
                (
                    "n8n_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Webhook response for debug/retry: status_code, sent_at, attempts.",
                    ),
                ),
                (
                    "server_render_time_ms",
                    models.FloatField(
                        blank=True,
                        help_text="View render time (time.monotonic). Performance monitoring.",
                        null=True,
                    ),
                ),
                (
                    "is_duplicate",
                    models.BooleanField(
                        default=False,
                        help_text="Same email + same launch already existed.",
                    ),
                ),
                (
                    "raw_utm_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Original UTM parameters as received from frontend. Preserved for re-parsing when naming conventions change.",
                    ),
                ),
                (
                    "ad_creative",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null if no parseable utm_content.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="ads.adcreative",
                    ),
                ),
                (
                    "ad_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null if organic without adset. Resolves -> campaign -> provider.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="ads.adgroup",
                    ),
                ),
                (
                    "capture_page",
                    models.ForeignKey(
                        help_text="Resolves everything: launch, interest, slug, n8n config.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="launches.capturepage",
                    ),
                ),
                (
                    "device_profile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Device dimension from VisitorMiddleware.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="tracking.deviceprofile",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        help_text="Resolved by ResolutionService. Always set (PHASE 3 guarantees).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capture_submissions",
                        to="contact_identity.identity",
                    ),
                ),
                (
                    "traffic_source",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null if direct traffic (no utm_source).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submissions",
                        to="ads.trafficsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capture Submission",
                "verbose_name_plural": "Capture Submissions",
                "db_table": "ads_capture_submission",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="adgroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id__gt", "")),
                fields=("campaign", "external_id"),
                name="unique_paid_adgroup",
            ),
        ),
        migrations.AddConstraint(
            model_name="adgroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", "")),
                fields=("campaign", "name"),
                name="unique_organic_adgroup",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="adplatform",
            unique_together={("provider", "code")},
        ),
        migrations.AddConstraint(
            model_name="adcreative",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id__gt", "")),
                fields=("provider", "external_id"),
                name="unique_paid_creative",
            ),
        ),
        migrations.AddConstraint(
            model_name="adcreative",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), ("full_code__gt", "")),
                fields=("provider", "full_code"),
                name="unique_organic_creative",
            ),
        ),
        migrations.AddConstraint(
            model_name="adcampaign",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id__gt", "")),
                fields=("provider", "external_id"),
                name="unique_paid_campaign",
            ),
        ),
        migrations.AddConstraint(
            model_name="adcampaign",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", "")),
                fields=("provider", "name", "launch"),
                name="unique_organic_campaign",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trafficsource",
            unique_together={("platform", "placement")},
        ),
        migrations.AddIndex(
            model_name="capturesubmission",
            index=models.Index(
                fields=["capture_page", "created_at"],
                name="ads_capture_capture_93c5de_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="capturesubmission",
            index=models.Index(
                fields=["capture_token"], name="ads_capture_capture_7327f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="capturesubmission",
            index=models.Index(
                fields=["n8n_status"], name="ads_capture_n8n_sta_3516a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="capturesubmission",
            index=models.Index(
                fields=["visitor_id", "created_at"],
                name="ads_capture_visitor_4379b0_idx",
            ),
        ),
    ]
