# Generated by Django 6.0.2 on 2026-02-16 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Record version for optimistic locking",
                        verbose_name="Version",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "default_list_id",
                    models.CharField(
                        blank=True,
                        help_text="Default CRM list ID for leads captured via this interest.",
                        max_length=50,
                    ),
                ),
                (
                    "default_thank_you_path",
                    models.CharField(
                        blank=True,
                        help_text="Default thank-you path, e.g. /obrigado-wh-rc-v3/",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "verbose_name": "Interest",
                "verbose_name_plural": "Interests",
                "db_table": "launches_interest",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Launch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Record version for optimistic locking",
                        verbose_name="Version",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "launch_code",
                    models.CharField(
                        help_text="Unique code, e.g. WH0126, BF2026.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "default_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Shared defaults for all pages: highlight_color, n8n webhook_url, form gradients, trust_badge, social_proof, etc.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Launch",
                "verbose_name_plural": "Launches",
                "db_table": "launches_launch",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CapturePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Record version for optimistic locking",
                        verbose_name="Version",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL slug, e.g. wh-rc-v3. Route: /inscrever-{slug}/",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name for admin identification.",
                        max_length=200,
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("capture", "Captura (email + phone)"),
                            ("waitlist", "Lista de espera (email only)"),
                            ("cpl", "CPL (conteudo + captura)"),
                            ("checkout", "Checkout (redirect para Stripe)"),
                            ("content", "Conteudo (blog, artigo)"),
                            ("sales", "Pagina de vendas"),
                        ],
                        default="capture",
                        max_length=20,
                    ),
                ),
                (
                    "layout_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard (single column)"),
                            ("two-column", "Two Column (Black Friday style)"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Page-specific config. Keys: meta, headline, subheadline, background_image, highlight_color, badges, form, trust_badge, social_proof, thank_you, n8n, topBanner, etc. Missing keys fall back to Launch.default_config.",
                    ),
                ),
                (
                    "n8n_webhook_url",
                    models.URLField(
                        blank=True,
                        help_text="N8N webhook URL for this page. Overrides launch default.",
                        max_length=500,
                    ),
                ),
                (
                    "n8n_list_id",
                    models.CharField(
                        blank=True,
                        help_text="CRM list ID for leads from this page.",
                        max_length=50,
                    ),
                ),
                (
                    "interest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pages",
                        to="launches.interest",
                    ),
                ),
                (
                    "launch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="launches.launch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capture Page",
                "verbose_name_plural": "Capture Pages",
                "db_table": "launches_capture_page",
                "ordering": ["slug"],
                "abstract": False,
            },
        ),
    ]
