# Generated by Django 6.0.2 on 2026-02-11 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted at"
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="Public ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Activated at"
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deactivated at"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data stored as JSON",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Record version for optimistic locking",
                        verbose_name="Version",
                    ),
                ),
                (
                    "utm_source",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="e.g., google, facebook, youtube",
                        max_length=255,
                        verbose_name="UTM Source",
                    ),
                ),
                (
                    "utm_medium",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="e.g., cpc, email, social",
                        max_length=255,
                        verbose_name="UTM Medium",
                    ),
                ),
                (
                    "utm_campaign",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="e.g., WH0126_launch, MDL0125_webinar",
                        max_length=255,
                        verbose_name="UTM Campaign",
                    ),
                ),
                (
                    "utm_content",
                    models.CharField(
                        blank=True,
                        help_text="e.g., banner_top, cta_bottom",
                        max_length=255,
                        verbose_name="UTM Content",
                    ),
                ),
                (
                    "utm_term",
                    models.CharField(
                        blank=True,
                        help_text="Keyword for paid search",
                        max_length=255,
                        verbose_name="UTM Term",
                    ),
                ),
                (
                    "referrer",
                    models.URLField(
                        blank=True, max_length=2048, verbose_name="Referrer URL"
                    ),
                ),
                (
                    "landing_page",
                    models.URLField(
                        blank=True, max_length=2048, verbose_name="Landing Page URL"
                    ),
                ),
                (
                    "touchpoint_type",
                    models.CharField(
                        blank=True,
                        default="form",
                        help_text="e.g., form, api, import, webhook",
                        max_length=50,
                        verbose_name="Touchpoint type",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributions",
                        to="contact_identity.identity",
                        verbose_name="Identity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attribution",
                "verbose_name_plural": "Attributions",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["identity", "-created_at"],
                        name="contact_ide_identit_36d8d5_idx",
                    ),
                    models.Index(
                        fields=["utm_source"], name="contact_ide_utm_sou_ff6f6d_idx"
                    ),
                    models.Index(
                        fields=["utm_campaign"], name="contact_ide_utm_cam_ca2020_idx"
                    ),
                ],
            },
        ),
    ]
